# CMake generated Testfile for 
# Source directory: D:/Projects/MilodikFX
# Build directory: D:/Projects/MilodikFX/build2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[MilodikFX_UnitTests]=] "D:/Projects/MilodikFX/build2/MilodikFX_tests_artefacts/Debug/MilodikFX_tests.exe")
  set_tests_properties([=[MilodikFX_UnitTests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/MilodikFX/CMakeLists.txt;170;add_test;D:/Projects/MilodikFX/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[MilodikFX_UnitTests]=] "D:/Projects/MilodikFX/build2/MilodikFX_tests_artefacts/Release/MilodikFX_tests.exe")
  set_tests_properties([=[MilodikFX_UnitTests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/MilodikFX/CMakeLists.txt;170;add_test;D:/Projects/MilodikFX/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[MilodikFX_UnitTests]=] "D:/Projects/MilodikFX/build2/MilodikFX_tests_artefacts/MinSizeRel/MilodikFX_tests.exe")
  set_tests_properties([=[MilodikFX_UnitTests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/MilodikFX/CMakeLists.txt;170;add_test;D:/Projects/MilodikFX/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[MilodikFX_UnitTests]=] "D:/Projects/MilodikFX/build2/MilodikFX_tests_artefacts/RelWithDebInfo/MilodikFX_tests.exe")
  set_tests_properties([=[MilodikFX_UnitTests]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/MilodikFX/CMakeLists.txt;170;add_test;D:/Projects/MilodikFX/CMakeLists.txt;0;")
else()
  add_test([=[MilodikFX_UnitTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[MilodikFX_Smoke]=] "powershell" "-ExecutionPolicy" "Bypass" "-File" "D:/Projects/MilodikFX/tests/smoke.ps1" "-AppPath" "D:/Projects/MilodikFX/build2/MilodikFX_artefacts/Debug/MilodikFX.exe")
  set_tests_properties([=[MilodikFX_Smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/MilodikFX/CMakeLists.txt;171;add_test;D:/Projects/MilodikFX/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[MilodikFX_Smoke]=] "powershell" "-ExecutionPolicy" "Bypass" "-File" "D:/Projects/MilodikFX/tests/smoke.ps1" "-AppPath" "D:/Projects/MilodikFX/build2/MilodikFX_artefacts/Release/MilodikFX.exe")
  set_tests_properties([=[MilodikFX_Smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/MilodikFX/CMakeLists.txt;171;add_test;D:/Projects/MilodikFX/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[MilodikFX_Smoke]=] "powershell" "-ExecutionPolicy" "Bypass" "-File" "D:/Projects/MilodikFX/tests/smoke.ps1" "-AppPath" "D:/Projects/MilodikFX/build2/MilodikFX_artefacts/MinSizeRel/MilodikFX.exe")
  set_tests_properties([=[MilodikFX_Smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/MilodikFX/CMakeLists.txt;171;add_test;D:/Projects/MilodikFX/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[MilodikFX_Smoke]=] "powershell" "-ExecutionPolicy" "Bypass" "-File" "D:/Projects/MilodikFX/tests/smoke.ps1" "-AppPath" "D:/Projects/MilodikFX/build2/MilodikFX_artefacts/RelWithDebInfo/MilodikFX.exe")
  set_tests_properties([=[MilodikFX_Smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/MilodikFX/CMakeLists.txt;171;add_test;D:/Projects/MilodikFX/CMakeLists.txt;0;")
else()
  add_test([=[MilodikFX_Smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[MilodikFX_Smoke_ASIO]=] "powershell" "-ExecutionPolicy" "Bypass" "-File" "D:/Projects/MilodikFX/tests/smoke-asio.ps1" "-AppPath" "D:/Projects/MilodikFX/build2/MilodikFX_artefacts/Debug/MilodikFX.exe" "-BuildDir" "D:/Projects/MilodikFX/build2")
  set_tests_properties([=[MilodikFX_Smoke_ASIO]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/MilodikFX/CMakeLists.txt;177;add_test;D:/Projects/MilodikFX/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[MilodikFX_Smoke_ASIO]=] "powershell" "-ExecutionPolicy" "Bypass" "-File" "D:/Projects/MilodikFX/tests/smoke-asio.ps1" "-AppPath" "D:/Projects/MilodikFX/build2/MilodikFX_artefacts/Release/MilodikFX.exe" "-BuildDir" "D:/Projects/MilodikFX/build2")
  set_tests_properties([=[MilodikFX_Smoke_ASIO]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/MilodikFX/CMakeLists.txt;177;add_test;D:/Projects/MilodikFX/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[MilodikFX_Smoke_ASIO]=] "powershell" "-ExecutionPolicy" "Bypass" "-File" "D:/Projects/MilodikFX/tests/smoke-asio.ps1" "-AppPath" "D:/Projects/MilodikFX/build2/MilodikFX_artefacts/MinSizeRel/MilodikFX.exe" "-BuildDir" "D:/Projects/MilodikFX/build2")
  set_tests_properties([=[MilodikFX_Smoke_ASIO]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/MilodikFX/CMakeLists.txt;177;add_test;D:/Projects/MilodikFX/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[MilodikFX_Smoke_ASIO]=] "powershell" "-ExecutionPolicy" "Bypass" "-File" "D:/Projects/MilodikFX/tests/smoke-asio.ps1" "-AppPath" "D:/Projects/MilodikFX/build2/MilodikFX_artefacts/RelWithDebInfo/MilodikFX.exe" "-BuildDir" "D:/Projects/MilodikFX/build2")
  set_tests_properties([=[MilodikFX_Smoke_ASIO]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/MilodikFX/CMakeLists.txt;177;add_test;D:/Projects/MilodikFX/CMakeLists.txt;0;")
else()
  add_test([=[MilodikFX_Smoke_ASIO]=] NOT_AVAILABLE)
endif()
subdirs("_deps/juce-build")
